permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
gems: [jekyll-paginate]

title : Simon Schneegans
tagline: Projects and Blog
author :
  name : Simon Schneegans
  email : admin@simonschneegans.de
  github : simmesimme

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://simmesimme.github.io

# you can specify your own separator, of course.
excerpt_separator: <!--more-->
paginate: 8
paginate_path: "blog/page:num/"

disqus_short_name : simonschneegans

defaults:
  -
    scope:
      path: ""
    values:
      parents: ["Blog"]
